version: "3.7"
services:
  db:
    image: mysql:5
    volumes:
      - ./order.sql:/docker-entrypoint-initdb.d/order.sql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80
  web:
    build: ./web
    volumes:
      - ./web/src:/var/www/html/
      - ./web/.htpasswd:/var/www/.htpasswd
    links:
      - db
    ports:
      - 8081:80