name: Publish

on:
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/publish.yml'

  # Allow manual trigger
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push app container image to registry
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.server
          push: true
          tags: ghcr.io/wk-laufen/musiorder:${{ github.sha }}
          platforms: linux/arm/v7,linux/arm64,linux/amd64

  build-nfc-reader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push app container image to registry
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.nfc-reader
          push: true
          tags: ghcr.io/wk-laufen/musiorder-nfc-reader:${{ github.sha }}
          platforms: linux/arm/v7,linux/arm64
